//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiConvertTimelineTypeRestRequestData: APIModel {

    public var comment: String?

    public var targetType: String?

    public init(comment: String? = nil, targetType: String? = nil) {
        self.comment = comment
        self.targetType = targetType
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        comment = try container.decodeIfPresent("comment")
        targetType = try container.decodeIfPresent("targetType")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(comment, forKey: "comment")
        try container.encodeIfPresent(targetType, forKey: "targetType")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiConvertTimelineTypeRestRequestData else { return false }
      guard self.comment == object.comment else { return false }
      guard self.targetType == object.targetType else { return false }
      return true
    }

    public static func == (lhs: ApiConvertTimelineTypeRestRequestData, rhs: ApiConvertTimelineTypeRestRequestData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
