//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiChangeContractDataRequest: APIModel {

    public var company: String?

    public var email: String?

    public var firstName: String?

    public var gender: String?

    public var lastName: String?

    public var password: String?

    public var phone: String?

    public init(company: String? = nil, email: String? = nil, firstName: String? = nil, gender: String? = nil, lastName: String? = nil, password: String? = nil, phone: String? = nil) {
        self.company = company
        self.email = email
        self.firstName = firstName
        self.gender = gender
        self.lastName = lastName
        self.password = password
        self.phone = phone
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        company = try container.decodeIfPresent("company")
        email = try container.decodeIfPresent("email")
        firstName = try container.decodeIfPresent("firstName")
        gender = try container.decodeIfPresent("gender")
        lastName = try container.decodeIfPresent("lastName")
        password = try container.decodeIfPresent("password")
        phone = try container.decodeIfPresent("phone")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(company, forKey: "company")
        try container.encodeIfPresent(email, forKey: "email")
        try container.encodeIfPresent(firstName, forKey: "firstName")
        try container.encodeIfPresent(gender, forKey: "gender")
        try container.encodeIfPresent(lastName, forKey: "lastName")
        try container.encodeIfPresent(password, forKey: "password")
        try container.encodeIfPresent(phone, forKey: "phone")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiChangeContractDataRequest else { return false }
      guard self.company == object.company else { return false }
      guard self.email == object.email else { return false }
      guard self.firstName == object.firstName else { return false }
      guard self.gender == object.gender else { return false }
      guard self.lastName == object.lastName else { return false }
      guard self.password == object.password else { return false }
      guard self.phone == object.phone else { return false }
      return true
    }

    public static func == (lhs: ApiChangeContractDataRequest, rhs: ApiChangeContractDataRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
