//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum ApiColour: String, Codable, Equatable, CaseIterable {
    case red = "RED"
    case green = "GREEN"
    case yellow = "YELLOW"
}
