//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiContract: APIModel {

    public var company: String?

    public var consents: [ApiUserConsent]?

    public var contractId: String?

    public var email: String?

    public var fields: [String: String]?

    public var firstName: String?

    public var gender: String?

    public var lastName: String?

    public var phone: String?

    public var registrationDate: String?

    public init(company: String? = nil, consents: [ApiUserConsent]? = nil, contractId: String? = nil, email: String? = nil, fields: [String: String]? = nil, firstName: String? = nil, gender: String? = nil, lastName: String? = nil, phone: String? = nil, registrationDate: String? = nil) {
        self.company = company
        self.consents = consents
        self.contractId = contractId
        self.email = email
        self.fields = fields
        self.firstName = firstName
        self.gender = gender
        self.lastName = lastName
        self.phone = phone
        self.registrationDate = registrationDate
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        company = try container.decodeIfPresent("company")
        consents = try container.decodeArrayIfPresent("consents")
        contractId = try container.decodeIfPresent("contractId")
        email = try container.decodeIfPresent("email")
        fields = try container.decodeIfPresent("fields")
        firstName = try container.decodeIfPresent("firstName")
        gender = try container.decodeIfPresent("gender")
        lastName = try container.decodeIfPresent("lastName")
        phone = try container.decodeIfPresent("phone")
        registrationDate = try container.decodeIfPresent("registrationDate")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(company, forKey: "company")
        try container.encodeIfPresent(consents, forKey: "consents")
        try container.encodeIfPresent(contractId, forKey: "contractId")
        try container.encodeIfPresent(email, forKey: "email")
        try container.encodeIfPresent(fields, forKey: "fields")
        try container.encodeIfPresent(firstName, forKey: "firstName")
        try container.encodeIfPresent(gender, forKey: "gender")
        try container.encodeIfPresent(lastName, forKey: "lastName")
        try container.encodeIfPresent(phone, forKey: "phone")
        try container.encodeIfPresent(registrationDate, forKey: "registrationDate")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiContract else { return false }
      guard self.company == object.company else { return false }
      guard self.consents == object.consents else { return false }
      guard self.contractId == object.contractId else { return false }
      guard self.email == object.email else { return false }
      guard self.fields == object.fields else { return false }
      guard self.firstName == object.firstName else { return false }
      guard self.gender == object.gender else { return false }
      guard self.lastName == object.lastName else { return false }
      guard self.phone == object.phone else { return false }
	  guard self.registrationDate == object.registrationDate else { return false }
      return true
    }

    public static func == (lhs: ApiContract, rhs: ApiContract) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
