//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiDeleteAccountRequest: APIModel {

    public var password: String?

    public init(password: String? = nil) {
        self.password = password
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        password = try container.decodeIfPresent("password")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(password, forKey: "password")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiDeleteAccountRequest else { return false }
      guard self.password == object.password else { return false }
      return true
    }

    public static func == (lhs: ApiDeleteAccountRequest, rhs: ApiDeleteAccountRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
