//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum ApiDistractionEventType: String, Codable, Equatable, CaseIterable {
    case phHheld = "PH_HHELD"
    case swpType = "SWP_TYPE"
}
