//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum ApiDBEType: String, Codable, Equatable, CaseIterable {
    case crn = "CRN"
    case acc = "ACC"
    case brk = "BRK"
}
