//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiGetMessagesResponseData: APIModel {

    public var deletedIds: [Int]?

    public var messages: [ApiMessage]?

    public init(deletedIds: [Int]? = nil, messages: [ApiMessage]? = nil) {
        self.deletedIds = deletedIds
        self.messages = messages
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        deletedIds = try container.decodeArrayIfPresent("deletedIds")
        messages = try container.decodeArrayIfPresent("messages")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(deletedIds, forKey: "deletedIds")
        try container.encodeIfPresent(messages, forKey: "messages")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiGetMessagesResponseData else { return false }
      guard self.deletedIds == object.deletedIds else { return false }
      guard self.messages == object.messages else { return false }
      return true
    }

    public static func == (lhs: ApiGetMessagesResponseData, rhs: ApiGetMessagesResponseData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
