//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiLogoutRequest: APIModel {

    public var contractId: String?

    public init(contractId: String? = nil) {
        self.contractId = contractId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        contractId = try container.decodeIfPresent("contractId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(contractId, forKey: "contractId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiLogoutRequest else { return false }
      guard self.contractId == object.contractId else { return false }
      return true
    }

    public static func == (lhs: ApiLogoutRequest, rhs: ApiLogoutRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
