//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiMoveTimelineResponseData: APIModel {

    public var timelineItemBaseList: [ApiMoveTimelineItemBase]?

    public init(timelineItemBaseList: [ApiMoveTimelineItemBase]? = nil) {
        self.timelineItemBaseList = timelineItemBaseList
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        timelineItemBaseList = try container.decodeArrayIfPresent("timelineItemBaseList")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(timelineItemBaseList, forKey: "timelineItemBaseList")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiMoveTimelineResponseData else { return false }
      guard self.timelineItemBaseList == object.timelineItemBaseList else { return false }
      return true
    }

    public static func == (lhs: ApiMoveTimelineResponseData, rhs: ApiMoveTimelineResponseData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
