//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiMoveTripSectionDistance: APIModel {

    public var green: Int?

    public var red: Int?

    public var yellow: Int?

    public init(green: Int? = nil, red: Int? = nil, yellow: Int? = nil) {
        self.green = green
        self.red = red
        self.yellow = yellow
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        green = try container.decodeIfPresent("green")
        red = try container.decodeIfPresent("red")
        yellow = try container.decodeIfPresent("yellow")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(green, forKey: "green")
        try container.encodeIfPresent(red, forKey: "red")
        try container.encodeIfPresent(yellow, forKey: "yellow")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiMoveTripSectionDistance else { return false }
      guard self.green == object.green else { return false }
      guard self.red == object.red else { return false }
      guard self.yellow == object.yellow else { return false }
      return true
    }

    public static func == (lhs: ApiMoveTripSectionDistance, rhs: ApiMoveTripSectionDistance) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
