//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiMoveTimelineDetailResponseData: APIModel {

    public var tripDetail: ApiMoveTimelineItemDetail?

    public init(tripDetail: ApiMoveTimelineItemDetail? = nil) {
        self.tripDetail = tripDetail
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        tripDetail = try container.decodeIfPresent("tripDetail")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(tripDetail, forKey: "tripDetail")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiMoveTimelineDetailResponseData else { return false }
      guard self.tripDetail == object.tripDetail else { return false }
      return true
    }

    public static func == (lhs: ApiMoveTimelineDetailResponseData, rhs: ApiMoveTimelineDetailResponseData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
