//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiProductAuthInfo: APIModel {

    public var accessToken: String?

    public var refreshToken: String?

    public init(accessToken: String? = nil, refreshToken: String? = nil) {
        self.accessToken = accessToken
        self.refreshToken = refreshToken
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        accessToken = try container.decodeIfPresent("accessToken")
        refreshToken = try container.decodeIfPresent("refreshToken")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(accessToken, forKey: "accessToken")
        try container.encodeIfPresent(refreshToken, forKey: "refreshToken")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiProductAuthInfo else { return false }
      guard self.accessToken == object.accessToken else { return false }
      guard self.refreshToken == object.refreshToken else { return false }
      return true
    }

    public static func == (lhs: ApiProductAuthInfo, rhs: ApiProductAuthInfo) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
