//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiRefreshTokenRequest: ApiBaseRequest {

    public var refreshToken: String?

    public init(timestamp: Int, appId: String? = nil, clientVersion: String? = nil, contractId: String? = nil, isoTime: String? = nil, language: String? = nil, platform: String? = nil, productId: Int? = nil, uuid: String? = nil, refreshToken: String? = nil) {
        self.refreshToken = refreshToken
        super.init(timestamp: timestamp, appId: appId, clientVersion: clientVersion, contractId: contractId, isoTime: isoTime, language: language, platform: platform, productId: productId, uuid: uuid)
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        refreshToken = try container.decodeIfPresent("refreshToken")
        try super.init(from: decoder)
    }

    public override func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(refreshToken, forKey: "refreshToken")
        try super.encode(to: encoder)
    }

    override public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiRefreshTokenRequest else { return false }
      guard self.refreshToken == object.refreshToken else { return false }
      return super.isEqual(to: object)
    }
}
