//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiRefreshTokenResponseData: APIModel {

    public var productAuthInfo: ApiProductAuthInfo?

    public init(productAuthInfo: ApiProductAuthInfo? = nil) {
        self.productAuthInfo = productAuthInfo
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        productAuthInfo = try container.decodeIfPresent("productAuthInfo")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(productAuthInfo, forKey: "productAuthInfo")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiRefreshTokenResponseData else { return false }
      guard self.productAuthInfo == object.productAuthInfo else { return false }
      return true
    }

    public static func == (lhs: ApiRefreshTokenResponseData, rhs: ApiRefreshTokenResponseData) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
