//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiTripRemovalReason: APIModel {

    public var id: Int

    public var reason: String?

    public init(id: Int, reason: String? = nil) {
        self.id = id
        self.reason = reason
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        id = try container.decode("id")
        reason = try container.decodeIfPresent("reason")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(id, forKey: "id")
        try container.encodeIfPresent(reason, forKey: "reason")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiTripRemovalReason else { return false }
      guard self.id == object.id else { return false }
      guard self.reason == object.reason else { return false }
      return true
    }

    public static func == (lhs: ApiTripRemovalReason, rhs: ApiTripRemovalReason) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
