//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum ApiTimelineItemType: String, Codable, Equatable, CaseIterable {
    case train = "TRAIN"
    case metro = "METRO"
    case walking = "WALKING"
    case unknown = "UNKNOWN"
    case car = "CAR"
    case bus = "BUS"
    case tram = "TRAM"
    case idle = "IDLE"
    case faketrip = "FAKETRIP"
    case publicTransport = "PUBLIC_TRANSPORT"
    case cycling = "CYCLING"
}
