//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiUpdateMessagesRequest: APIModel {

    public var messages: [ApiMessage]?

    public init(messages: [ApiMessage]? = nil) {
        self.messages = messages
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        messages = try container.decodeArrayIfPresent("messages")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(messages, forKey: "messages")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiUpdateMessagesRequest else { return false }
      guard self.messages == object.messages else { return false }
      return true
    }

    public static func == (lhs: ApiUpdateMessagesRequest, rhs: ApiUpdateMessagesRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
