//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ApiValidateEmailHashRequest: APIModel {

    public var hash: String?

    public init(hash: String? = nil) {
        self.hash = hash
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        hash = try container.decodeIfPresent("hash")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(hash, forKey: "hash")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ApiValidateEmailHashRequest else { return false }
      guard self.hash == object.hash else { return false }
      return true
    }

    public static func == (lhs: ApiValidateEmailHashRequest, rhs: ApiValidateEmailHashRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
