//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension API.MoveUserRest {

    /** Returns information about user's contract. Non-generic (product-specific) attributes are returned in the 'fields' map. */
    public enum GetApiV1Users {

        public static let service = APIService<Response>(id: "getApiV1Users", tag: "MoveUserRest", method: "GET", path: "/api/v1/users", hasBody: false, securityRequirements: [SecurityRequirement(type: "clientName", scopes: []), SecurityRequirement(type: "clientName", scopes: [])])

        public final class Request: APIRequest<Response> {

            public struct Options {

                public var xAppAppversion: String?

                public var xAppAppid: String?

                public var acceptLanguage: String?

                public var date: String?

                public var xAppContractid: String?

                public init(xAppAppversion: String? = nil, xAppAppid: String? = nil, acceptLanguage: String? = nil, date: String? = nil, xAppContractid: String? = nil) {
                    self.xAppAppversion = xAppAppversion
                    self.xAppAppid = xAppAppid
                    self.acceptLanguage = acceptLanguage
                    self.date = date
                    self.xAppContractid = xAppContractid
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetApiV1Users.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(xAppAppversion: String? = nil, xAppAppid: String? = nil, acceptLanguage: String? = nil, date: String? = nil, xAppContractid: String? = nil) {
                let options = Options(xAppAppversion: xAppAppversion, xAppAppid: xAppAppid, acceptLanguage: acceptLanguage, date: date, xAppContractid: xAppContractid)
                self.init(options: options)
            }

            override var headerParameters: [String: String] {
                var headers: [String: String] = [:]
                if let xAppAppversion = options.xAppAppversion {
                  headers["x-app-appversion"] = xAppAppversion
                }
                if let xAppAppid = options.xAppAppid {
                  headers["x-app-appid"] = xAppAppid
                }
                if let acceptLanguage = options.acceptLanguage {
                  headers["Accept-Language"] = String(describing: acceptLanguage)
                }
                if let date = options.date {
                  headers["Date"] = date
                }
                if let xAppContractid = options.xAppContractid {
                  headers["x-app-contractid"] = xAppContractid
                }
                return headers
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = ApiGetContractResponse

            /** Request was successful */
            case status200(ApiGetContractResponse)

            /** An unexpected error occurred while processing the request. */
            case defaultResponse(statusCode: Int, ApiBaseResponse)

            public var success: ApiGetContractResponse? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var failure: ApiBaseResponse? {
                switch self {
                case .defaultResponse(_, let response): return response
                default: return nil
                }
            }

            /// either success or failure value. Success is anything in the 200..<300 status code range
            public var responseResult: APIResponseResult<ApiGetContractResponse, ApiBaseResponse> {
                if let successValue = success {
                    return .success(successValue)
                } else if let failureValue = failure {
                    return .failure(failureValue)
                } else {
                    fatalError("Response does not have success or failure response")
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                case .defaultResponse(_, let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .defaultResponse(let statusCode, _): return statusCode
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .defaultResponse: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(ApiGetContractResponse.self, from: data))
                default: self = try .defaultResponse(statusCode: statusCode, decoder.decode(ApiBaseResponse.self, from: data))
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
